# [LightGBM Quantile] Ingesting synchronized contract datasets...
# [Feature Contract] Building unified pre-scheduling feature whitelist...
# [Leakage Audit] PASS - no forbidden predictors in model feature contract.
# [Feature Contract] Total predictors: 1587
# [Feature Contract] Procedure indicators: 1572
# [Feature Contract] Train shape: (41983, 1587)
# [Feature Contract] Test shape: (17083, 1587)
# [LightGBM Quantile] Fitting non-parametric quantile estimation matrices...
# [LightGBM Quantile]  Enforcing post-hoc monotonic quantile correction...
# [LightGBM Quantile] Evaluating predictive quantiles on the temporally held-out test cohort...

# ===========================================================================
#  LIGHTGBM QUANTILE EVALUATION REPORT
#  TEMPORALLY HELD-OUT TEST COHORT: 2022-01-01 TO 2023-08-10
# ===========================================================================
#    Target P10 Lower Bound Coverage Limit (True >= P10) : 90.00%
#    Empirical P10 Lower Bound Coverage                  : 90.19%
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
#    P50 Mean Absolute Error (minutes)                   : 74.76
# ---------------------------------------------------------------------------
#    Target P90 Upper Bound Coverage Limit (True <= P90) : 90.00%
#    Empirical P90 Upper Bound Coverage                  : 89.74%
# ---------------------------------------------------------------------------
#    Target Interquantile Interval Range [P10, P90]       : 80.00%
#    Empirical Interquantile Interval Coverage           : 79.93%
# ===========================================================================

# [LightGBM Quantile] Synchronizing predictive decision assets to optimization data layer...
# SUCCESS! Decision artifacts generated: Prescriptive/LightGBM_prescriptive_optimizer_inputs.csv
# Array shape: (17083, 4) (17083 temporally held-out cases).
import pandas as pd
import numpy as np
import os
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import mean_absolute_error
import lightgbm as lgb

# ==========================================
# 1. DATA INGESTION AND COHORT LOADING
# ==========================================
train_input = "new_data/mover_epic_final_train_features.csv"
test_input = "new_data/mover_epic_final_test_features.csv"

print("[LightGBM Quantile] Ingesting synchronized contract datasets...")
if not os.path.exists(train_input) or not os.path.exists(test_input):
    raise FileNotFoundError("Missing essential upstream processed cohort files.")

train_df = pd.read_csv(train_input, encoding='utf-8')
test_df = pd.read_csv(test_input, encoding='utf-8')

# ==========================================
# 2. LEAKAGE-FREE FEATURE CONTRACT
# ==========================================
print("[Feature Contract] Building unified pre-scheduling feature whitelist...")

# Continuous / ordinal numerical predictors
scaler_features = [
    'AGE',
    'HEIGHT',
    'WEIGHT',
    'SURGERY_DAY_OF_WEEK',
    'SURGERY_MONTH'
]

# Cyclical calendar encodings derived from SURGERY_DATE
cyclical_features = [
    'DOW_SIN',
    'DOW_COS',
    'MONTH_SIN',
    'MONTH_COS'
]

# Binary preoperative indicators
binary_features = [
    'SEX_CODE',
    'Is_Hypertension',
    'Is_Diabetes',
    'Is_Cardiac'
]

# ASA physical-status category
categorical_features = [
    'ASA_RATING_C'
]

# Procedure indicators generated by train-fitted OneHotEncoder upstream
procedure_cols = sorted([
    c for c in train_df.columns
    if c.startswith('PRIMARY_PROCEDURE_NM_')
])

# Explicit preoperative interaction
interaction_cols = [
    'INTERACT_AGE_ASA'
]

# Unified feature contract used identically across all predictive models
feature_cols = sorted(
    scaler_features
    + cyclical_features
    + binary_features
    + categorical_features
    + procedure_cols
    + interaction_cols
)

forbidden_exact_features = {
    'SCHEDULED_START_HOUR',
    'IS_MORNING_CASE',
    'IS_MORNING_CASE_CODE',
    'HOUR_SIN',
    'HOUR_COS',
    'ICU_ADMIN_FLAG',
    'ICU_ADMIN_FLAG_CODE',
    'DISCH_DISP',
    'AN_START_DATETIME',
    'AN_STOP_DATETIME',
    'WHEELS_IN',
    'WHEELS_OUT',
    'IN_OR_DTTM',
    'OUT_OR_DTTM'
}

forbidden_prefixes = (
    'INTERACT_ICU_x_',
)

# Explicitly forbidden interaction
forbidden_exact_features.add(
    'INTERACT_HOUR_MORNING'
)

detected_forbidden = [
    col for col in feature_cols
    if (
        col in forbidden_exact_features
        or col.startswith(forbidden_prefixes)
    )
]

assert not detected_forbidden, (
    "Leakage-control failure. Forbidden predictors detected: "
    f"{detected_forbidden}"
)

print(
    "[Leakage Audit] PASS - no forbidden predictors "
    "in model feature contract."
)


# Defensive schema validation
missing_train = sorted(set(feature_cols) - set(train_df.columns))
missing_test = sorted(set(feature_cols) - set(test_df.columns))

if missing_train:
    raise ValueError(
        f"Training cohort missing required features: {missing_train}"
    )

if missing_test:
    raise ValueError(
        f"Test cohort missing required features: {missing_test}"
    )

X_train = train_df[feature_cols].copy()
X_test = test_df[feature_cols].copy()

y_train_raw = train_df['ACTUAL_DURATION'].copy()
y_train_log = np.log1p(y_train_raw)

y_test_true = test_df['ACTUAL_DURATION'].copy()

print(f"[Feature Contract] Total predictors: {len(feature_cols)}")
print(f"[Feature Contract] Procedure indicators: {len(procedure_cols)}")
print(f"[Feature Contract] Train shape: {X_train.shape}")
print(f"[Feature Contract] Test shape: {X_test.shape}")

# ==========================================
# 3. ENCAPSULATED PREPROCESSOR PIPELINE
# ==========================================
continuous_features = (
    scaler_features
    + cyclical_features
    + interaction_cols
)

num_pipe = Pipeline([
    (
        'imputer',
        SimpleImputer(strategy='median')
    ),
    (
        'scaler',
        StandardScaler(
            with_mean=True,
            with_std=True
        )
    )
])

bin_pipe = Pipeline([
    (
        'imputer',
        SimpleImputer(
            strategy='constant',
            fill_value=0
        )
    )
])

cat_pipe = Pipeline([
    (
        'imputer',
        SimpleImputer(
            strategy='most_frequent'
        )
    )
])

preprocessor = ColumnTransformer(
    transformers=[
        (
            'num_flow',
            num_pipe,
            continuous_features
        ),
        (
            'bin_flow',
            bin_pipe,
            binary_features
        ),
        (
            'cat_flow',
            cat_pipe,
            categorical_features
        ),
        (
            'proc_flow',
            'passthrough',
            procedure_cols
        )
    ],
    remainder='drop'
)

# ==========================================
# 4. LIGHTGBM MULTI-QUANTILE PIPELINE EXECUTION
# ==========================================
print("[LightGBM Quantile] Fitting non-parametric quantile estimation matrices...")

quantiles = [0.1, 0.5, 0.9]
raw_quantile_outputs = {}

# Train 3 disjoint tree architectures targeting asymmetric check losses natively inside log space
for q in quantiles:
    pipe_lgb_q = Pipeline([
        ('preprocess', preprocessor),
        ('model', lgb.LGBMRegressor(
            objective='quantile',
            alpha=q,
            n_estimators=100,
            learning_rate=0.05,
            num_leaves=31,
            random_state=42,
            n_jobs=-1,
            verbose=-1
        ))
    ])
    pipe_lgb_q.fit(X_train, y_train_log)
    
    # Generate log forecasts and invert immediately back to raw clinical minutes
    raw_quantile_outputs[f'P{int(q*100)}'] = np.expm1(pipe_lgb_q.predict(X_test))

# ==========================================
# 5. POST-HOC MONOTONIC QUANTILE CORRECTION
# ==========================================
print("[LightGBM Quantile]  Enforcing post-hoc monotonic quantile correction...")

p10_raw = raw_quantile_outputs['P10']
p50_pred = raw_quantile_outputs['P50'] # P50 serves as the median anchor line
p90_raw = raw_quantile_outputs['P90']

# Core Fix: Project monotonic bounds mathematically to strip away quantile crossing violations (P10 > P50 or P50 > P90)
p10_corrected = np.minimum(p10_raw, p50_pred)
p90_corrected = np.maximum(p50_pred, p90_raw)

# ==========================================
# 6. DOUBLE-TAIL SYMMETRICAL COVERAGE VALIDATION AUDIT
# ==========================================
print("[LightGBM Quantile] Evaluating predictive quantiles on the temporally held-out test cohort...")

true_vals = y_test_true.to_numpy(dtype=np.float64)
p10_coverage = np.mean(true_vals >= p10_corrected) * 100
p90_coverage = np.mean(true_vals <= p90_corrected) * 100
interval_coverage = np.mean((true_vals >= p10_corrected) & (true_vals <= p90_corrected)) * 100
p50_mae = mean_absolute_error(
    true_vals,
    p50_pred
)


print("\n" + "="*75)
print(" LIGHTGBM QUANTILE EVALUATION REPORT")
print(" TEMPORALLY HELD-OUT TEST COHORT: 2022-01-01 TO 2023-08-10")
print("="*75)
print(f"   Target P10 Lower Bound Coverage Limit (True >= P10) : 90.00%")
print(f"   Empirical P10 Lower Bound Coverage                  : {p10_coverage:.2f}%")
print("-"*75)
print(f"   P50 Mean Absolute Error (minutes)                   : {p50_mae:.2f}")
print("-"*75)
print(f"   Target P90 Upper Bound Coverage Limit (True <= P90) : 90.00%")
print(f"   Empirical P90 Upper Bound Coverage                  : {p90_coverage:.2f}%")
print("-"*75)
print(f"   Target Interquantile Interval Range [P10, P90]       : 80.00%")
print(f"   Empirical Interquantile Interval Coverage           : {interval_coverage:.2f}%")
print("="*75 + "\n")


# ==========================================
# 7. EXPORT PREDICTIVE QUANTILES FOR DOWNSTREAM MILP
# ==========================================

print(
    "[LightGBM Quantile] Synchronizing predictive "
    "decision assets to optimization data layer..."
)

optimizer_payload = pd.DataFrame({
    'LOG_ID': test_df['LOG_ID'].values,
    'DURATION_P10_MINS': p10_corrected,
    'DURATION_P50_MINS': p50_pred,
    'DURATION_P90_MINS': p90_corrected
})

# Defensive integrity checks
assert len(optimizer_payload) == len(test_df)

assert not optimizer_payload[
    [
        'DURATION_P10_MINS',
        'DURATION_P50_MINS',
        'DURATION_P90_MINS'
    ]
].isna().any().any(), "NaN detected in optimizer quantile predictions."

assert np.all(
    optimizer_payload['DURATION_P10_MINS']
    <= optimizer_payload['DURATION_P50_MINS']
), "P10 > P50 detected after monotonic correction."

assert np.all(
    optimizer_payload['DURATION_P50_MINS']
    <= optimizer_payload['DURATION_P90_MINS']
), "P50 > P90 detected after monotonic correction."

os.makedirs("Prescriptive", exist_ok=True)

output_optimizer_file = (
    "Prescriptive/LightGBM_prescriptive_optimizer_inputs.csv"
)

optimizer_payload.to_csv(
    output_optimizer_file,
    index=False,
    encoding='utf-8'
)

print(
    f"SUCCESS! Decision artifacts generated: "
    f"{output_optimizer_file}"
)

print(
    f"Array shape: {optimizer_payload.shape} "
    f"({len(optimizer_payload)} temporally held-out cases)."
)